Don't capitalize error messages, use %q instead of \"%s\"
From staticcheck:

	code93/encoder.go:70:15: error strings should not be capitalized (ST1005)
	code93/encoder.go:101:16: error strings should not end with punctuation or newlines (ST1005)

The main reason for this is so that error messages" chain nicer; for
example in my code:

	img, err := qr.Encode(..)
	if err != nil {
		return fmt.Errorf("failed to create image: %w", err)
	}

Which looks nicer without capital:

	failed to create image: too much data to encode
	failed to create image: Too much data to encode

Also:

- replace some instances of \"%s\" with %q; the %q will add the quotes,
  and will also escape quotes.

- correct some instances of "to much" to "too much".